name: robbins
favicon: null
layout_spectrum: 0.0322170986328274
typography_spectrum: 0.8322615511715412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8983761761337519
  lightness: 0.9863672754727304
  saturation: 0.9819539457093924
  rhythmicContrast: 0.4263924283441156
purpose: []
